"""empty message

Revision ID: 486b230f1f36
Revises: 6735414ea296
Create Date: 2021-07-22 17:17:46.377700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '486b230f1f36'
down_revision = '6735414ea296'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saved', sa.Column('contentSource', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('saved', 'contentSource')
    # ### end Alembic commands ###
