"""empty message

Revision ID: 9fd082dd664d
Revises: c5ab4546c252
Create Date: 2021-08-16 15:18:55.490223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fd082dd664d'
down_revision = 'c5ab4546c252'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saved', sa.Column('publishedTime', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('saved', 'publishedTime')
    # ### end Alembic commands ###
