"""empty message

Revision ID: 651d18ec1328
Revises: 8eb69e81cb36
Create Date: 2021-07-11 18:20:15.925999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '651d18ec1328'
down_revision = '8eb69e81cb36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('default',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('itemURL', sa.String(), nullable=False),
    sa.Column('imageURL', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('imageURL'),
    sa.UniqueConstraint('itemURL')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('default')
    # ### end Alembic commands ###
