"""empty message

Revision ID: c5ab4546c252
Revises: 486b230f1f36
Create Date: 2021-07-22 17:36:42.126805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5ab4546c252'
down_revision = '6735414ea296'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saved', sa.Column('contentSource', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('saved', 'contentSource')
    # ### end Alembic commands ###
