"""empty message

Revision ID: 4d89ab4fce74
Revises: 1511d66bb82a
Create Date: 2021-07-10 21:00:37.973616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d89ab4fce74'
down_revision = '1511d66bb82a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saved', sa.Column('description', sa.String(), nullable=True))
    op.add_column('saved', sa.Column('imageURL', sa.String(), nullable=False))
    op.add_column('saved', sa.Column('title', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'saved', ['itemURL'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'saved', type_='unique')
    op.drop_column('saved', 'title')
    op.drop_column('saved', 'imageURL')
    op.drop_column('saved', 'description')
    # ### end Alembic commands ###
